version: '3'
services:
  epochtalk-vue:
    build: .
    ports:
      - "80:80"
    links:
      - epochtalk
  epochtalk:
    image: quay.io/epochtalk/epochtalk:ui-refactor-2020
    ports:
      - "8080:8080"
      - "23958:23958"
    depends_on:
      - redis
      - postgres
      - epoch
    links:
      - redis
      - postgres
    env_file:
      - epochtalk-docker.env
  epoch:
    image: quay.io/epochtalk/epoch:v1.13.0
    depends_on:
      - postgres
    links:
      - postgres
    environment:
      MIX_ENV: prod
      DATABASE_USER: docker
      DATABASE_PASSWORD: docker
      DATABASE_NAME: epochtalk
      DATABASE_HOST: postgres
  redis:
    image: redis:4.0.1
    user: redis
  postgres:
    image: postgres:11.1
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
