version: 2.1
jobs:
  release:
    docker:
      - image: circleci/node:12.14.1
    steps:
      - checkout
      - run: yarn install
      - run:
          command: npx semantic-release
          no_output_timeout: 5m
workflows:
  version: 2
  release:
    - release
